- cmasher/utils.py
I have written a fairly simple function to turn any colormap into a qualitative one (i.e a single colour between two values).
I haven't written any tests for it, but I have run pytest on my computer and it doesn't seem to break anything (and passes flake8.
Let me know if there is anything I should change or fix before you can merge it. I wasn't sure about the naming style you would prefer for this function. I went with 'create', but I think 'make' or 'generate' would also work.
> Added create_qualitative_cmap function

- .github/workflows/test.yml
- pyproject.toml
I will also add explicit support for Python 3.10 to 3.12 in another PR, after I'm done reviving CI.
> MNT: drop support for EOL Python versions 3.6 and 3.7

- .github/workflows/test.yml
this is a temporary measure to stop the bleeding so I can focus on fixing CI one job at a time
> MNT: temporarily deactivate cross-plateform CI

- .github/workflows/lint_python.yml
This is a temporary measure to hopefully get CI green again.
> MNT: temporarily disable safety check

- cmasher/cli_tools.py
- pyproject.toml
e13tools isn't compatible with Python 3.12 because it has an undeclared runtime dependency on `setuptools`, and it uses `pkg_resources`, which is deprecated as an API
> DEP: drop dependency on e13tools (broken on Python 3.12)

- .github/workflows/test.yml
- cmasher/cm.py
- cmasher/utils.py
- pyproject.toml
Python 3.8 is borderline "EOL" within scientific Python, so as it is making maintenance more difficult, I'm dropping it.
> MNT: drop support for Python 3.8

- .github/workflows/test.yml
I discovered in https://github.com/1313e/CMasher/actions/runs/7237227888/job/19716623262?pr=84 that the ecosystem is now pretty hostile to this arch so there's not much we can do about it except dropping it.
> TST: drop support for Windows x86 (32 bits arch)

- pyproject.toml
- requirements.txt
> MNT: bump minimal requirement for numpy (1.17.3 -> 1.19.3)

- conftest.py
> TST: detect and avoid test pollution

- .github/dependabot.yml
I enabled dependabot auto updates in two months ago in #59. However, since then, we didn't get any pull requests, and I'm seeing warnings that some actions are out of date, so let's try this noop change to force dependabot to notice this repo (this trick was recommended by GitHub support).
> MNT: try to force dependabot to re-index us

- .github/workflows/test.yml
- pyproject.toml
- requirements/dev.txt
- requirements/min_constraints.txt
in #129, I brutally bumped minimum numpy from 1.19.3 to 1.23.0 . Let's try to roll this back a little.
> TST: revert numpy bump

- src/cmasher/utils.py
1) stating that the colormap is "invalid" is confusing since there's a lot more than a single failure mode
2) we don't need to re-include the original error message since we're explicitly chaining exceptions already
> UX: clarify generic error message when failing to import/register a colormap

- README.rst
- docs/source/user/introduction.rst
- docs/source/user/usage.rst
- joss_paper/paper.md
The `cmasher/colormaps` directory was moved to `src/cmasher/colormaps`. This PR adjusts sources to changes.
> DOC: Update cmasher/colormaps references

- .github/workflows/test.yml
Fix a silent conflict between #153 and #157: `uv run` will (re)install the project by default, in editable mode.
> TST: don't use editable install in CI (again)

- .readthedocs.yaml
fix an invalid configuration I apparently introduced in #152 but didn't notice until now.
```
Config file validation error
Config validation error in build.tools.python. Expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, miniconda3-4.7, miniconda3-3.12-24.1, mambaforge-4.10, mambaforge-22.9, mambaforge-23.11, 3, latest, miniconda-latest, mambaforge-latest), got type str (3.13). Double check the type of the value. A string may be required (e.g. "3.10" instead of 3.10)
```
> MNT: fix ReadTheDocs builds

- tests/test_utils.py
Fixes a mistake introduced in #153 which lead to the reapearance of a bug initially fixed in #101.
Close #167.
> TST: fix internal filter (discard `__pycache__` as a colormap directory)

- tests/test_utils.py
I noticed that a couple tests were taking a large fraction of testing time. On my machine, this change means running the whole suite goes from ~15s to ~3s.
> TST: speedup slow tests by using only a sample of all colormaps

- tests/test_utils.py
In the spirit of #177, this further reduces the run time of our longest test.
> TST: speedup longest test by targetting a smaller colormap set

- .github/workflows/test.yml
- pyproject.toml
- uv.lock
Context: numpy 2.2.0 just dropped and CMasher does not typecheck against it. Not all errors seem genuine and I may not have time to address/report all of them soon, so I'm stabilizing CI with a lock file.
> TST: rewrite CI around `uv.lock`

- .readthedocs.yaml
shameful follow up to #191, #192, #193, #194
This time I verified that the command runs locally.
> DOC: fixup RTD (when will it end)

- pyproject.toml
- src/cmasher/utils.py
- uv.lock
originated from #204
This patch has become large enough to warrant its own PR
> TYP: improve type annotations for `create_cmap_overview` and streamline internal logic to improve type-checkability

- src/cmasher/utils.py
- **TYP: avoid uppercase for non-constants variable names**
- **TYP: minor fixes around numpy APIs**
- **TYP: avoid 'possibly unbound' warnings for internal var ax1**
- **TYP: improve type annotations for get_cmap_list**
- **TYP: improve type annotations for take_cmap_colors**
> TYP: fix a couple more type checking errors flagged by pyright

- pyproject.toml
`flit-core` is far less complex than `hatchling`, and we don't actually need any of the latter's features, so, let's keep things as simple as possible for maximal portability.
Incidentally, remove avoids shipping `.gitignore` as part of source distributions.
> BLD: migrate build backend to `flit-core`
