- .github/workflows/lint_python.yml
- joss_paper/paper.md
https://github.com/codespell-project/codespell#codespell
> GitHub Action to lint Python code

- cmasher/tests/test_utils.py
- cmasher/utils.py
Fix instabilities due to current-day `matplotlib` raising an error in case of re-registration.
> TST: fix utility tests

- cmasher/colormaps/prep_cmap_data.py
- cmasher/utils.py
> API: remove deprecated colormap alias (heat -> torch)

- requirements.txt
> MNT: cleanup unused requirement

- cmasher/cli_tools.py
- cmasher/tests/test_utils.py
- cmasher/utils.py
> BUG: fix compatibility with matplotlib 3.5

- cmasher/_handlercolorpolycollection.py
- cmasher/utils.py
- pyproject.toml
this helps reducing startup time.
> ENH: delay expensive imports

- .github/workflows/test.yml
same as #98 but for the dev branch
> MNT: fix auto-publication, also publish a wheel

- .github/workflows/lint_python.yml
- .github/workflows/test.yml
Initially just wanted to refactor the call to `uv pip compile` to avoid creating a requirement file, but I ended up just ditching pip completely.
> TST: speed up env resolution with uv

- .github/workflows/test.yml
- .pre-commit-config.yaml
- .readthedocs.yaml
- cmasher/utils.py
- pyproject.toml
- requirements/min_constraints.txt
- requirements/typecheck.txt
> DEP: drop support for Python 3.9

- .github/workflows/test.yml
- conftest.py
- pyproject.toml
- src/cmasher/tests/test_utils.py
- src/cmasher/utils.py
> TST: reintroduce coverage measurement and improve coverage to 100% (excluding defensive programming lines)

- .github/workflows/test.yml
> TST: fix coverage report combination

- pyproject.toml
- uv.lock
Solves the current blocker for https://github.com/1313e/CMasher/pull/188
> DEP: manually set resolution constraints for PyQt5-Qt5 to workaround uv's current blindspots

- uv.lock
> DEP: upgrade uv.lock (pyqt5-qt5, pyqt5-sip)

- .readthedocs.yaml
follow up to #192 where I forgot to adapt the install command
> DOC: fixup RTD

- .readthedocs.yaml
follow up to #391 and #392 (third time's the charm ?)
> DOC: fixup RTD (again)

- .readthedocs.yaml
> DOC: fixup RTD (final ?)

- src/cmasher/utils.py
> TYP: replace CMAP type alias with an explicit union

- src/cmasher/utils.py
fix a minor (unreleased) bug introduced in #205
> BUG: only label cmap categories if requested in create_cmap_overview

- src/cmasher/utils.py
another small follow up to #205
> RFC: rename internal variables (drop unneeded leading underscores)

- src/cmasher/_handlercolorpolycollection.py
Most remaining errors (~30) seem a lot less trivial to fix, especially because of missing stubs in numpy (e.g. `np.around` still returns `Any`), but I figured I might as well commit my progress because one of the errors corresponds to an actual runtime bug.
> TYP: fix a couple errors flagged by pyright
